// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wyvhuoknwisagdpbwhfh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind5dmh1b2tud2lzYWdkcGJ3aGZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwMjc4MjcsImV4cCI6MjA2ODYwMzgyN30.rSHtfNiuw63-fhZC0WtlDYJqBMMFW_w-q-z80j6s28Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});